### PR TITLE
Feature/milestone 1

### PR DESCRIPTION
**Pull request by zilton7**
In This Milestone:
- Installs big.js.
- Installs PropTypes.
- Installs Eslint and Stylint.
- Pushes to Heroku

Thanks for the review ;)

### CODE REVIEW

**Comment by mimipeshy** [comment]
## STATUS : CHANGES REQUESTED 🔴 ♻️ 
Hello @vidhishweta01 👋🏾 👋🏾 congratulations on making it this far 😄 . 

#### Highlights

-  You have met almost all the requirements needed for this milestone✔️ 

#### To improve
Kindly work on the following ⬇️ 
- [x] The project needs to have a descriptive README.md. To be descriptive the README needs simply to include the title of the project, a description about it, and instructions on how to set up and run the project.([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

- [x]  Your PR is invalid.Pull Request should always have a meaningful title and a brief description ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)) 

That's all 😄, kindly submit another review when done
If you need any clarification, kindly post your comment here and tag me @mimipeshy and will be glad to help

Regards,
Peris Ndanu

**Comment by vidhishweta01** [comment]
Hi, I don't know why I am mentioned here I am not a contributed to this project

**Comment by vidhishweta01** [comment]
Hi, I don't know why I am mentioned here I am not a contributed to this project

**Comment by zilton7** [comment]
> Hi, I don't know why I am mentioned here I am not a contributed to this project

yes, I have noticed that, probably reviewer mixed up our names :)

**Review by mikenath223 — CHANGES_REQUESTED** [review]
n/a

**Review by mikenath223 — APPROVED** [review]
### CONGRATULATIONS  👏👏👏

This project meets the requirements for approval.

**STATUS: APPROVED ✅**


Don't forget to fill the project completion form👍
Good luck with the next project.

**HAPPY CODING 🎉💻🎉**

**Michgolden Ukeje (CR)**

**Pull request merged**
